=== bradh/military_xml_project_miliconvert/miliconvert/xsmt-docs/trunk/testing/xsd/fourwhisky.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema attributeFormDefault="unqualified"
	elementFormDefault="qualified" version="11"
	xmlns:xsd="http://www.w3.org/2001/XMLSchema">
	<xsd:element name="fourwhisky">
		<xsd:complexType>
			<xsd:choice maxOccurs="unbounded" minOccurs="0">
				<xsd:element maxOccurs="1" minOccurs="1"
					name="message_identification">
					<xsd:complexType>
						<xsd:sequence>
							<xsd:element maxOccurs="1" minOccurs="1" name="command" />
							<xsd:element maxOccurs="1" minOccurs="1"
								name="message_identifier" />
							<xsd:element maxOccurs="1" minOccurs="1"
								name="message_serial_no" />
							<xsd:element maxOccurs="1" minOccurs="1" name="month" />
							<xsd:element maxOccurs="1" minOccurs="0" name="operexer_name" />
							<xsd:element maxOccurs="1" minOccurs="0" name="qualifier" />
							<xsd:element maxOccurs="1" minOccurs="0"
								name="qualifier_serial_no" />
						</xsd:sequence>
						<xsd:attribute name="setId" type="xsd:string" use="required" />
						<xsd:attribute name="set-seq" type="xsd:string" use="required" />
					</xsd:complexType>
				</xsd:element>
				<xsd:element maxOccurs="1" minOccurs="0" name="security">
					<xsd:complexType>
						<xsd:sequence>
							<xsd:element maxOccurs="1" minOccurs="1" name="classification" />
							<xsd:element maxOccurs="1" minOccurs="0"
								name="amplifying_info" />
						</xsd:sequence>
						<xsd:attribute name="setId" type="xsd:string" use="required" />
						<xsd:attribute name="set-seq" type="xsd:string" use="required" />
					</xsd:complexType>
				</xsd:element>
				<xsd:element maxOccurs="unbounded" minOccurs="0"
					name="addressees">
					<xsd:complexType>
						<xsd:sequence>
							<xsd:element maxOccurs="1" minOccurs="1" name="address" />
							<xsd:element maxOccurs="1" minOccurs="0" name="address_1" />
							<xsd:element maxOccurs="1" minOccurs="0" name="address_2" />
							<xsd:element maxOccurs="1" minOccurs="0" name="address_3" />
							<xsd:element maxOccurs="1" minOccurs="0" name="address_4" />
							<xsd:element maxOccurs="1" minOccurs="0" name="address_5" />
							<xsd:element maxOccurs="1" minOccurs="0" name="address_6" />
							<xsd:element maxOccurs="1" minOccurs="0" name="address_7" />
							<xsd:element maxOccurs="1" minOccurs="0" name="address_8" />
						</xsd:sequence>
						<xsd:attribute name="setId" type="xsd:string" use="required" />
						<xsd:attribute name="set-seq" type="xsd:string" use="required" />
					</xsd:complexType>
				</xsd:element>
				<xsd:element maxOccurs="1" minOccurs="1" name="_4-whisky">
					<xsd:complexType>
						<xsd:sequence>
							<xsd:element maxOccurs="1" minOccurs="1" name="name" />
							<xsd:element maxOccurs="1" minOccurs="1"
								name="no_of_grid_cells" />
							<xsd:element maxOccurs="1" minOccurs="1" name="grid_cell_size" />
							<xsd:element maxOccurs="1" minOccurs="1" name="pim_cell" />
							<xsd:element maxOccurs="1" minOccurs="0" name="remarks" />
						</xsd:sequence>
						<xsd:attribute name="setId" type="xsd:string" use="required" />
						<xsd:attribute name="set-seq" type="xsd:string" use="required" />
					</xsd:complexType>
				</xsd:element>
				<xsd:element maxOccurs="unbounded" minOccurs="1"
					name="_4-whisky_unit">
					<xsd:complexType>
						<xsd:sequence>
							<xsd:element maxOccurs="1" minOccurs="1" name="unit_name" />
							<xsd:element maxOccurs="1" minOccurs="1"
								name="unit_assignment" />
						</xsd:sequence>
						<xsd:attribute name="setId" type="xsd:string" use="required" />
						<xsd:attribute name="set-seq" type="xsd:string" use="required" />
					</xsd:complexType>
				</xsd:element>
				<xsd:element maxOccurs="1" minOccurs="1" name="end_of_data">
					<xsd:complexType>
						<xsd:sequence>
							<xsd:element maxOccurs="1" minOccurs="0"
								name="derivation_source_for_clsif" />
							<xsd:element maxOccurs="unbounded" minOccurs="0"
								name="dwngrd_or_declass_inst" />
							<xsd:element maxOccurs="unbounded" minOccurs="0"
								name="dwngrd_or_declass_exempt_code" />
						</xsd:sequence>
						<xsd:attribute name="setId" type="xsd:string" use="required" />
						<xsd:attribute name="set-seq" type="xsd:string" use="required" />
					</xsd:complexType>
				</xsd:element>
			</xsd:choice>
		</xsd:complexType>
	</xsd:element>
</xsd:schema>

=== bradh/military_xml_project_miliconvert/miliconvert/xsmt-docs/trunk/testing/v2/recette_v2/test_v2_06/xml/fourw_CELAR_02.othtgold.xml
<?xml version="1.0" encoding="UTF-8"?>
<fourwhisky xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="fourwhisky.xsd">
<message_identification set-seq="40" setId="MSGID">
<command ff-seq="1">VAUMILICONVERT</command>
<message_identifier ff-seq="2">4WHISKY</message_identifier>
<message_serial_no ff-seq="3">26184</message_serial_no>
<month ff-seq="4">JAN</month>
<operexer_name ff-seq="5">PEACOMLL</operexer_name>
<qualifier ff-seq="6">PER</qualifier>
<qualifier_serial_no ff-seq="7">012</qualifier_serial_no>
</message_identification>
<security set-seq="41" setId="SEC">
<classification ff-seq="1">CONFIDENTIAL</classification>
<amplifying_info ff-seq="2">SPECIAL FRANCE</amplifying_info>
</security>
<addressees set-seq="42" setId="ADDEE">
<address ff-seq="1">GCCS-M</address>
<address_1 ff-seq="2">GCCS-M</address_1>
<address_2 ff-seq="3">GCCS-M</address_2>
<address_3 ff-seq="4">GCCS-M</address_3>
<address_4 ff-seq="5">GCCS-M</address_4>
<address_5 ff-seq="6">GCCS-M</address_5>
<address_6 ff-seq="7">GCCS-M</address_6>
</addressees>
<addressees set-seq="42" setId="ADDEE">
<address ff-seq="1">GCCS-M</address>
<address_1 ff-seq="2">GCCS-M</address_1>
<address_2 ff-seq="3">GCCS-M</address_2>
<address_3 ff-seq="4">GCCS-M</address_3>
<address_4 ff-seq="5">GCCS-M</address_4>
<address_5 ff-seq="6">GCCS-M</address_5>
<address_6 ff-seq="7">GCCS-1</address_6>
</addressees>
<addressees set-seq="42" setId="ADDEE">
<address ff-seq="1">GCCS-M</address>
<address_1 ff-seq="2">GCCS-M</address_1>
<address_2 ff-seq="3">GCCS-M</address_2>
<address_3 ff-seq="4">GCCS-M</address_3>
<address_4 ff-seq="5">GCCS-M</address_4>
<address_5 ff-seq="6">GCCS-M</address_5>
<address_6 ff-seq="7">GCCS-2</address_6>
</addressees>
<_4-whisky set-seq="43" setId="WHSKY">
<name ff-seq="1">SARKOZY</name>
<no_of_grid_cells ff-seq="2">36</no_of_grid_cells>
<grid_cell_size ff-seq="3">10NM</grid_cell_size>
<pim_cell ff-seq="4">N13</pim_cell>
<remarks ff-seq="5">CEST UN TEST</remarks>
</_4-whisky>
<_4-whisky_unit set-seq="44" setId="WUNIT">
<unit_name ff-seq="1">CV</unit_name>
<unit_assignment ff-seq="2">QT1520</unit_assignment>
</_4-whisky_unit>
<_4-whisky_unit set-seq="44" setId="WUNIT">
<unit_name ff-seq="1">DE</unit_name>
<unit_assignment ff-seq="2">JL0812</unit_assignment>
</_4-whisky_unit>
<_4-whisky_unit set-seq="44" setId="WUNIT">
<unit_name ff-seq="1">AO</unit_name>
<unit_assignment ff-seq="2">XZ0812</unit_assignment>
</_4-whisky_unit>
<_4-whisky_unit set-seq="44" setId="WUNIT">
<unit_name ff-seq="1">FF</unit_name>
<unit_assignment ff-seq="2">JL2428+LM2526</unit_assignment>
</_4-whisky_unit>
<_4-whisky_unit set-seq="44" setId="WUNIT">
<unit_name ff-seq="1">EISENHOWER DD</unit_name>
<unit_assignment ff-seq="2">CF04+C0506+F0506</unit_assignment>
</_4-whisky_unit>
<_4-whisky_unit set-seq="44" setId="WUNIT">
<unit_name ff-seq="1">ENTERPRISE</unit_name>
<unit_assignment ff-seq="2">DM1219</unit_assignment>
</_4-whisky_unit>
<end_of_data set-seq="45" setId="ENDAT">
<derivation_source_for_clsif ff-seq="1">CNO (N10) LTR SER GS123456 OF 20JAN00</derivation_source_for_clsif>
<dwngrd_or_declass_inst ff-seq="2">INST:UPON COMPLETION</dwngrd_or_declass_inst>
<dwngrd_or_declass_exempt_code ff-seq="3">OF PROJECT BIG JUMP</dwngrd_or_declass_exempt_code>
</end_of_data>
</fourwhisky>

=== bradh/military_xml_project_miliconvert/miliconvert/xsmt-docs/trunk/testing/v2/recette_v2/test_v2_06/xml/fourw_CELAR_04.othtgold.xml
<?xml version="1.0" encoding="UTF-8"?>
<fourwhisky xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="fourwhisky.xsd">
<message_identification set-seq="40" setId="MSGID">
<command ff-seq="1">-</command>
<message_identifier ff-seq="2">4WHISKY</message_identifier>
<message_serial_no ff-seq="3">0001</message_serial_no>
<month ff-seq="4">FEB</month>
<operexer_name ff-seq="5">JULIEN</operexer_name>
</message_identification>
<_4-whisky set-seq="43" setId="WHSKY">
<name ff-seq="1">ZONE JULIEN</name>
<no_of_grid_cells ff-seq="2">30</no_of_grid_cells>
<grid_cell_size ff-seq="3">30NM</grid_cell_size>
<pim_cell ff-seq="4">Q15</pim_cell>
</_4-whisky>
<_4-whisky_unit set-seq="44" setId="WUNIT">
<unit_name ff-seq="1">TOTO</unit_name>
<unit_assignment ff-seq="2">H25+P22+Q15+L17+L20+Q20+Q21+R20+R21</unit_assignment>
</_4-whisky_unit>
<end_of_data set-seq="45" setId="ENDAT"/>
</fourwhisky>

=== bradh/military_xml_project_miliconvert/miliconvert/xsmt-docs/trunk/testing/v2/recette_v2/test_v2_06/xml/fourw.othtgold.xml
<?xml version="1.0" encoding="UTF-8"?>
<fourwhisky xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="fourwhisky.xsd">
<message_identification set-seq="40" setId="MSGID">
<command ff-seq="1">CTG 81.0</command>
<message_identifier ff-seq="2">4WHISKY</message_identifier>
<message_serial_no ff-seq="3">0007</message_serial_no>
<month ff-seq="4">JAN</month>
</message_identification>
<security set-seq="41" setId="SEC">
<classification ff-seq="1">UNCLASSIFIED</classification>
</security>
<addressees set-seq="42" setId="ADDEE">
<address ff-seq="1">GCCS-M</address>
</addressees>
<_4-whisky set-seq="43" setId="WHSKY">
<name ff-seq="1">REAGAN</name>
<no_of_grid_cells ff-seq="2">36</no_of_grid_cells>
<grid_cell_size ff-seq="3">10NM</grid_cell_size>
<pim_cell ff-seq="4">N13</pim_cell>
</_4-whisky>
<_4-whisky_unit set-seq="44" setId="WUNIT">
<unit_name ff-seq="1">CV</unit_name>
<unit_assignment ff-seq="2">QT1520</unit_assignment>
</_4-whisky_unit>
<_4-whisky_unit set-seq="44" setId="WUNIT">
<unit_name ff-seq="1">DE</unit_name>
<unit_assignment ff-seq="2">JL0812</unit_assignment>
</_4-whisky_unit>
<_4-whisky_unit set-seq="44" setId="WUNIT">
<unit_name ff-seq="1">AO</unit_name>
<unit_assignment ff-seq="2">XZ0812</unit_assignment>
</_4-whisky_unit>
<_4-whisky_unit set-seq="44" setId="WUNIT">
<unit_name ff-seq="1">FF</unit_name>
<unit_assignment ff-seq="2">JL2428+LM2526</unit_assignment>
</_4-whisky_unit>
<end_of_data set-seq="45" setId="ENDAT"/>
</fourwhisky>
